In [22]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import glob
import os

In [23]:
# combine all 2022 monthly data files into single csv file
# merging the files
#files_joined = os.path.join('C:\\Users\\DELL\\OneDrive\\Desktop\\CSV_files', "salesdata*.csv")

# Return a list of all joined files
list_files = glob.glob("data/*.csv")

print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
df = pd.concat(map(pd.read_csv, list_files), ignore_index=True)

print(df)

** Merging multiple csv files into a single pandas dataframe **
        tripduration                 starttime                  stoptime  \
0                226  2020-01-01 00:04:50.1920  2020-01-01 00:08:37.0370
1                377  2020-01-01 00:16:01.6700  2020-01-01 00:22:19.0800
2                288  2020-01-01 00:17:33.8770  2020-01-01 00:22:22.4420
3                435  2020-01-01 00:32:05.9020  2020-01-01 00:39:21.0660
4                231  2020-01-01 00:46:19.6780  2020-01-01 00:50:11.3440
...              ...                       ...                       ...
336797          1750  2020-12-31 23:07:44.0030  2020-12-31 23:36:54.4710
336798          1519  2020-12-31 23:18:00.2630  2020-12-31 23:43:19.8590
336799          1761  2020-12-31 23:31:09.4620  2021-01-01 00:00:31.3290
336800           637  2020-12-31 23:35:45.4640  2020-12-31 23:46:22.7300
336801          1607  2020-12-31 23:48:34.5750  2021-01-01 00:15:22.3090

        start station id start station name  start station latitude  \
0                   3186      Grove St PATH               40.719586
1                   3186      Grove St PATH               40.719586
2                   3186      Grove St PATH               40.719586
3                   3195            Sip Ave               40.730897
4                   3186      Grove St PATH               40.719586
...                  ...                ...                     ...
336797              3199       Newport Pkwy               40.728745
336798              3184        Paulus Hook               40.714145
336799              3195            Sip Ave               40.730897
336800              3681           Grand St               40.715178
336801              3267       Morris Canal               40.712419

        start station longitude  end station id  end station name  \
0                    -74.043117            3211        Newark Ave
1                    -74.043117            3269   Brunswick & 6th
2                    -74.043117            3269   Brunswick & 6th
3                    -74.063913            3280       Astor Place
4                    -74.043117            3276  Marin Light Rail
...                         ...             ...               ...
336797               -74.032108            3199      Newport Pkwy
336798               -74.033552            3195           Sip Ave
336799               -74.063913            3270   Jersey & 6th St
336800               -74.037683            3199      Newport Pkwy
336801               -74.038526            3267      Morris Canal

        end station latitude  end station longitude  bikeid    usertype  \
0                  40.721525             -74.046305   29444  Subscriber
1                  40.726012             -74.050389   26305  Subscriber
2                  40.726012             -74.050389   29268    Customer
3                  40.719282             -74.071262   29278    Customer
4                  40.714584             -74.042817   29276  Subscriber
...                      ...                    ...     ...         ...
336797             40.728745             -74.032108   40440    Customer
336798             40.730897             -74.063913   46340    Customer
336799             40.725289             -74.045572   40907    Customer
336800             40.728745             -74.032108   42250    Customer
336801             40.712419             -74.038526   48742  Subscriber

        birth year  gender
0             1984       2
1             1989       2
2             1989       1
3             1969       0
4             1983       2
...            ...     ...
336797        1969       0
336798        1969       0
336799        1998       1
336800        1969       0
336801        1982       1

[336802 rows x 15 columns]

In [24]:
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [25]:
#df.drop(['start station latitude', 'start station longitude','end station latitude','end station longitude'], axis=1, inplace=True)
#df.head()

In [26]:
df['date'] = pd.to_datetime(df['starttime'])

# add a column for Year
df['year'] = df['date'].dt.year
# add a column for Month
df['month'] = df['date'].dt.month
# add a column for Day
df['day'] = df['date'].dt.day
# add a column for Day of the Year
df['dayofyear'] = df['date'].dt.dayofyear
# add a column for Day of the Year
df['hour'] = df['date'].dt.hour

#age
df['age'] = df['year'] - df['birth year']

df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,usertype,birth year,gender,date,year,month,day,dayofyear,hour,age
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,...,Subscriber,1984,2,2020-01-01 00:04:50.192,2020,1,1,1,0,36
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,...,Subscriber,1989,2,2020-01-01 00:16:01.670,2020,1,1,1,0,31
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,...,Customer,1989,1,2020-01-01 00:17:33.877,2020,1,1,1,0,31
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,...,Customer,1969,0,2020-01-01 00:32:05.902,2020,1,1,1,0,51
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,...,Subscriber,1983,2,2020-01-01 00:46:19.678,2020,1,1,1,0,37

In [27]:
df.to_csv("data/combined_data.csv")